// <auto-generated />
using System;
using MemberQfit.Services.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MemberQfit.Services.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240510170803_addSeedData4")]
    partial class addSeedData4
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MemberQfit.Services.API.Models.Members", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AboutMe")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Age")
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Gender")
                        .HasColumnType("int");

                    b.Property<double?>("Height")
                        .HasColumnType("float");

                    b.Property<string>("Job")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("JoinDate")
                        .HasColumnType("date");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MobileNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NIC")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Weight")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Members");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "No 1, Colombo",
                            Email = "john@gmail.com",
                            FirstName = "John",
                            JoinDate = new DateOnly(2024, 5, 10),
                            LastName = "Doe",
                            MobileNumber = "0786589235",
                            NIC = "123456789V"
                        },
                        new
                        {
                            Id = 2,
                            Address = "No 1, Negombo",
                            Email = "Luni@gmail.com",
                            FirstName = "Jane",
                            JoinDate = new DateOnly(2024, 5, 10),
                            LastName = "Deo",
                            MobileNumber = "0786589235",
                            NIC = "123456789V"
                        },
                        new
                        {
                            Id = 3,
                            Address = "No 1, Dankotuwa",
                            Email = "Luni@gmail.com",
                            FirstName = "Sunil",
                            JoinDate = new DateOnly(2024, 5, 10),
                            LastName = "Gamage",
                            MobileNumber = "0786589235",
                            NIC = "991202548V"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
